data:
  instruct_data: "/opt/ml/code/datasets/test_gen-00000-of-00001-3d4cd8309148a71f/train.jsonl"
  eval_instruct_data: "/opt/ml/code/datasets/test_gen-00000-of-00001-3d4cd8309148a71f/eval.jsonl"
  data: ""

model_id_or_path: "mistralai/Mistral-7B-v0.3"  # This will be overridden if model is provided in SM_CHANNEL_MODEL

lora:
  rank: 8

# optim
seq_len: 128
batch_size: 4
max_steps: 1000
optim:
  lr: 6e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100

save_adapters: True

run_dir: "/opt/ml/model"

wandb:
  project: "mistral-7b-test"
  run_name: "mistral-7b-sagemaker"
  offline: True
