data:
  instruct_data: "/opt/ml/input/data/train"
  eval_instruct_data: "/opt/ml/input/data/test"
  data: ""

model_id_or_path: "/opt/ml/input/data/model"

lora:
  rank: 8

seq_len: 128
batch_size: 4
max_steps: 1000
optim:
  lr: 6e-5
  weight_decay: 0.1
  pct_start: 0.05

seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100

save_adapters: True

run_dir: "/opt/ml/model"

wandb:
  project: "mistral-7b-test"
  run_name: "mistral-7b-sagemaker"
  offline: True
  key: "106e694fa8054eab04e2ee0f788fc56c3b65a522"
