batch_size: 4
ckpt_freq: 100
data:
  data: ''
  eval_instruct_data: /opt/ml/input/data/test
  instruct_data: /opt/ml/input/data/train
eval_freq: 100
log_freq: 1
lora:
  rank: 8
max_steps: 1000
model_id_or_path: /opt/ml/input/data/model
no_eval: false
optim:
  lr: 6e-5
  pct_start: 0.05
  weight_decay: 0.1
run_dir: /opt/ml/model
save_adapters: true
seed: 0
seq_len: 128
wandb:
  key: 106e694fa8054eab04e2ee0f788fc56c3b65a522
  offline: true
  project: None
  run_name: mistral-7b-sagemaker
